; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Fri Nov 02 2018 00:19:11 GMT-0400 (Eastern Daylight Time)
M561 ; clear any bed transform
; Probe the bed at 4 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y110 H0 Z-99999
G30 P2 X105 Y110 H0 Z-99999
G30 P3 X105 Y15 H0 Z-99999 S