; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Fri Nov 02 2018 00:19:12 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0